[
  ./chromium.nix
  ./firefox.nix
  ./misc/flatpak.nix
  ./misc/spotify.nix
  ./misc/gallery-dl.nix
  ./dev/vscode.nix
  ./dev/vim.nix
  ./utils/git.nix
  ./utils/gpg.nix
  ./utils/bashrc.nix
  ./utils/zshrc.nix
  ./utils/utils.nix
]
