name: "Update flakes"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.ACCESS_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          pr-labels: |
            merge-queue
